version: "3"
services:
  service1:
    build: ./webapp1
    ports:
      - "8081:80"
    volumes:
      - app-data1:/data
    
  service2:
    build: ./webapp2
    ports:
      - "8082:80"
    volumes:
      - app-data2:/data

  service3:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2


volumes:
  app-data1:
  app-data2:

